.PHONY: all
all: main

main: main.o lib.o
	gcc -o main main.o lib.o

main.o: main.c
	gcc -c main.c -o main.o

lib.o: lib.c
	gcc -c lib.c -o lib.o

.PHONY: clean
clean:
	rm -f *.o main


$@ => name of target e.g main, main.o, lib.o

$% => target member name
    if target is foo.a(bar.o), then $@ => foo.a and $% => bar.o

$< => name of the first prerequisite (after the target:)
    e.g main.o, main.c, lib.c

$^ => names of all prerequisite (after the target:)



CC = gcc
CFLAGS += -Wall -Wextra -Werror
LINKERFLAG = -lm
SOURCES = my_mastermind.c functions.h info.h
OBJECTS = $(SOURCES: .c=.o)
TARGET = my_mastermind

$(TARGET) : $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^

.PHONY: clean fclean re

clean:
	@rm -f *.o

fclean:
	@rm $(TARGET0)
	$(clean)

re:
	$(fclean)
	$(MAKE)