# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'sinatra'
gem 'sqlite3'
gem 'activerecord'
gem 'rake'
gem 'pry'
gem 'sinatra-activerecord'
gem 'require_all'
gem 'shotgun'
gem 'thin'
gem 'bcrypt'
gem 'tux'
gem 'rack-flash3'
gem 'sinatra-flash'